pipeline {
    agent { label 'rhel7-8gb' }

    stages {
        stage('Run Vert.x tests against nightly build') {
            steps {
                build job: 'basic-MultiUser-Che-check-E2E-Happy-path-tests-against-k8s',
                        parameters: [
                                string(name: 'cheImageRepo',
                                        value: 'eclipse/che-server'),

                                string(name: 'cheImageTag',
                                        value: 'nightly'),

                                booleanParam(name: 'buildChe',
                                        value: false),

                                string(name: 'ghprbSourceBranch',
                                        value: 'che-15397'),

                                string(name: 'ghprbPullId',
                                        value: ''),

                                string(name: 'e2eTestToRun',
                                        value: 'test-java-vertx'),

                                string(name: 'testWorkspaceDevfileUrl',
                                        value: ''),

                                text(name: 'customResourceFileContent',
                                        value: ''),

                                booleanParam(name: 'createTestWorkspace',
                                        value: false)
                        ]            }
        }
    }
}