#!/bin/bash

exec /opt/jboss/keycloak/bin/standalone.sh \
        -Dkeycloak.migration.action=import \
        -Dkeycloak.migration.provider=dir \
        -Dkeycloak.migration.strategy=IGNORE_EXISTING \
        -Dkeycloak.migration.dir=/opt/jboss/keycloak/realms/ \
        -Djboss.bind.address=0.0.0.0

