#!/bin/bash
# Copyright (c) 2012-2017 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

exec start-keycloak.sh \
     -Dkeycloak.migration.action=import \
     -Dkeycloak.migration.provider=dir \
     -Dkeycloak.migration.strategy=IGNORE_EXISTING \
     -Dkeycloak.migration.dir=/opt/jboss/keycloak/realms/ \
     -Djboss.bind.address=0.0.0.0

