#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: che
    component: postgres
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che
      component: postgres
  template:
    metadata:
      labels:
        app: che
        component: postgres
        io.kompose.service: postgres
    spec:
      securityContext:
        runAsUser: 26
        fsGroup: 26
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: keycloak
        - name: POSTGRESQL_PASSWORD
          value: keycloak
        - name: POSTGRESQL_DATABASE
          value: keycloak
        - name: "CHE_POSTGRES_USERNAME"
          value: "pgche"
        - name: "CHE_POSTGRES_PASSWORD"
          value: "pgchepassword"
        - name: "CHE_POSTGRES_DATABASE"
          value: "dbche"
        {{- if .Values.global.postgresDebugLogs }}
        - name: "POSTGRESQL_LOG_DEBUG"
          value: "true"
        {{- end }}
        image: {{ .Values.image }}
        securityContext:
          runAsUser: 26
        imagePullPolicy: Always
        name: postgres
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - psql -h 127.0.0.1 -U ${POSTGRESQL_USER} -q -d $POSTGRESQL_DATABASE -c "SELECT 1"
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgres-data
      restartPolicy: Always
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
status: {}
