#!/bin/bash
# Copyright (c) 2012-2017 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

echo "Directory contents of /tmp/src:"
ls -a /tmp/src
echo ""

echo "Directory contents of /tmp/s2i:"
ls -a /tmp/scripts
echo ""

echo "Adding the user initialization script into directory: /var/lib/pgsql/data/userdata/ ..."
cp -v /tmp/src/init-che-user.sh.erb /var/run/postgresql/init-che-user.sh

