#!groovy

pipeline {
    agent { label params.jenkinsNodeLabel }

    options {
        timestamps()
        timeout(time: 40, unit: 'MINUTES')
        buildDiscarder(logRotator(artifactDaysToKeepStr: '',
                artifactNumToKeepStr: '', daysToKeepStr: '60', numToKeepStr: '100'))
    }

    environment {
        JENKINS_BUILD = "true"

        DEVFILE_URL = "${WORKSPACE}/e2e/files/happy-path/happy-path-workspace.yaml"
        SUCCESS_THRESHOLD = 5
    }

    stages {
        stage("Download OKD") {
            steps {
                script {
                    echo "to do"
                }
            }
        }

        stage("Start OKD") {
            steps {
                script {
                    echo "to do"
                }
            }
        }

        stage("Start Single Che") {
            steps {
                script {
                    echo "to do"
                }
            }
        }

        stage("Create test workspace") {
            steps {
                script {
                    sh "${WORKSPACE}/chectl workspace:start --devfile=$DEVFILE_URL"
                }
            }
        }

        stage("Run E2E Happy path tests") {
            steps {
                script {
                    // TO-DO (#14171) switch to eclipse/che-e2e image
//                    sh """
//                         CHE_HOST=\$(kubectl get ingress che-ingress -n=che -o=jsonpath={'.spec.rules[0].host'})
//                         CHE_URL=http://\${CHE_HOST}
//                         docker run --shm-size=256m --net=host --ipc=host \\
//                           -e TS_SELENIUM_HEADLESS='true' \\
//                           -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 \\
//                           -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=240000 \\
//                           -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 \\
//                           -e TS_SELENIUM_BASE_URL=\${CHE_URL} \\
//                           -v ${WORKSPACE}/e2e:/root/local_tests:Z \\
//                           eclipse/che-e2e:nightly
//                     """

                    sh """
                        CHE_HOST=\$(kubectl get ingress che-ingress -n=che -o=jsonpath={'.spec.rules[0].host'})
                        CHE_URL=http://\${CHE_HOST}
                        docker run --net=host --ipc=host \\
                           -e TS_SELENIUM_HEADLESS='true' \\
                           -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 \\
                           -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=240000 \\
                           -e TS_SELENIUM_BASE_URL=\${CHE_URL} \\
                           -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 \\
                           -w /home/e2e \\
                           -v $WORKSPACE:/home:Z \\
                           cypress/browsers:node8.9.3-chrome73 bash -c "npm install &&  npm run test-happy-path"
                    """
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: "e2e/report/**"

            script {
                sh """
                      oc get configmaps --namespace=che che -o yaml || true
                    """
            }

            cleanWs notFailBuild: true, disableDeferredWipeout: true, deleteDirs: true
        }

    }

}
