pipeline {
    agent { label 'rhel7-8gb' }

    stages {
        stage('Run Happy path tests against nightly build') {
            steps {
                build job: 'basic-MultiUser-Che-check-E2E-Happy-path-tests-against-k8s',
                        parameters: [
                                string(name: 'cheImageRepo',
                                        value: 'eclipse/che-server'),

                                string(name: 'cheImageTag',
                                        value: 'nightly'),

                                booleanParam(name: 'buildChe',
                                        value: false),

                                string(name: 'ghprbAuthorRepoGitUrl',
                                        value: 'https://github.com/eclipse/che.git'),

                                string(name: 'ghprbSourceBranch',
                                        value: 'che-15397'),

                                string(name: 'ghprbPullId',
                                        value: ''),

                                string(name: 'e2eTestToRun',
                                        value: 'test-happy-path'),

                                string(name: 'testWorkspaceDevfileUrl',
                                        value: 'https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml'),

                                text(name: 'customResourceFileContent',
                                        value: ''),

                                booleanParam(name: 'createTestWorkspace',
                                        value: true)
                        ]            }
        }
    }
}