/*******************************************************************************
 * Copyright (c) 2012-2017 Red Hat, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 *******************************************************************************/
package org.eclipse.che.plugin.pullrequest.shared;

/**
 * Constants for PullRequest Workflow API
 */
public final class Constants {

    /**
     * Property value for Pull Request workflow feature: If property is true (default),
     * then generates a Factory URL embedded within the PR generated by Che for provider
     * that manages the pull request. The PR factory is a URL that generates a workspace
     * that contains the commit of the PR itself. Setting this to false will generate a
     * PR without an embedded Factory URL. Generate PRs using the pull request panel
     * in the IDE.
     */
    public static final String CHE_PR_GENERATE_REVIEW_FACTORY_PROP = "che.pr";

    private Constants() {
    }
}
