pipeline {
    agent { label 'rhel7-8gb' }

    environment {
        String customResourceFileContent = ""
    }

    parameters {
        string(name: 'RELEASE_BRANCH',
                defaultValue: "7.5.x",
                description: 'Branch with pre-release version to take E2E Happy path test.')

        string(name: 'RELEASE_VERSION',
                defaultValue: "7.5.0",
                description: 'Version of Che-theia')
    }

    stages {
        stage('Patch custom-resource.yaml') {
            steps {
                script {
                        String customResourceFilePath = "${WORKSPACE}/custom-resource.yaml"

                        sh """
                                wget https://raw.githubusercontent.com/eclipse/che-operator/master/deploy/crds/org_v1_che_cr.yaml \\
                                -O $customResourceFilePath
                        """

                        customResourceFileContent = readFile customResourceFilePath
                        customResourceFileContent = customResourceFileContent.replace("eclipse/che-keycloak:nightly", "eclipse/che-keycloak:rc")
                        customResourceFileContent = customResourceFileContent.replace("quay.io/eclipse/che-devfile-registry:nightly", "quay.io/eclipse/che-devfile-registry:$RELEASE_VERSION")
                        customResourceFileContent = customResourceFileContent.replace("quay.io/eclipse/che-plugin-registry:nightly", "quay.io/eclipse/che-plugin-registry:$RELEASE_VERSION")

                        echo "$customResourceFileContent"
                }
            }
        }

        stage('Run Vert.x tests against Eclipse Che release candidate') {
            steps {
                script {
                        build job: 'basic-MultiUser-Che-check-E2E-Happy-path-tests-against-k8s',
                                parameters: [
                                        string(name: 'cheImageRepo',
                                                value: 'eclipse/che-server'),

                                        string(name: 'cheImageTag',
                                                value: 'rc'),

                                        booleanParam(name: 'buildChe',
                                                value: false),

                                        string(name: 'ghprbAuthorRepoGitUrl',
                                                value: 'https://github.com/eclipse/che.git'),

                                        string(name: 'ghprbSourceBranch',
                                                value: "$RELEASE_BRANCH"),

                                        string(name: 'ghprbPullId',
                                                value: ''),

                                        string(name: 'e2eTestToRun',
                                                value: 'test-java-vertx'),

                                        string(name: 'testWorkspaceDevfileUrl',
                                                value: ""),

                                        text(name: 'customResourceFileContent',
                                                value: "$customResourceFileContent"),

                                        booleanParam(name: 'createTestWorkspace',
                                                value: false)
                                ]
                }
            }
        }
    }
}