#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if .Values.global.tls.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: che-host-cert
spec:
  secretName: {{ .Values.global.tls.secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.global.cheDomain }}
  dnsNames:
      - {{ .Values.global.cheDomain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.global.cheDomain }}
{{- end }}
