pipeline {
    agent { label 'rhel7-8gb' }

    stages {
        stage("Run E2E tests against master branch") {
            parallel {
                stage('Run Happy path tests') {
                    steps {
                        build job: 'basic-MultiUser-Che-check-E2E-Happy-path-tests-against-k8s',
                                parameters: [
                                        string(name: 'cheImageRepo',
                                                value: 'maxura/che-server'),

                                        string(name: 'cheImageTag',
                                                value: 'master'),

                                        booleanParam(name: 'buildChe',
                                                value: true),

                                        string(name: 'ghprbSourceBranch',
                                                value: 'che-15397'),

                                        string(name: 'ghprbPullId',
                                                value: ''),

                                        string(name: 'e2eTestToRun',
                                                value: 'test-happy-path'),

                                        string(name: 'testWorkspaceDevfileUrl',
                                                value: 'https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml'),

                                        text(name: 'customResourceFileContent',
                                                value: ''),

                                        booleanParam(name: 'createTestWorkspace',
                                                value: true)
                                ]
                    }
                }

                stage('Run Vert.x tests') {
                    steps {
                        build job: 'basic-MultiUser-Che-check-E2E-Happy-path-tests-against-k8s',
                                parameters: [
                                        string(name: 'cheImageRepo',
                                                value: 'maxura/che-server'),

                                        string(name: 'cheImageTag',
                                                value: 'master'),

                                        booleanParam(name: 'buildChe',
                                                value: true),

                                        string(name: 'ghprbSourceBranch',
                                                value: 'che-15397'),

                                        string(name: 'ghprbPullId',
                                                value: ''),

                                        string(name: 'e2eTestToRun',
                                                value: 'test-java-vertx'),

                                        string(name: 'testWorkspaceDevfileUrl',
                                                value: ''),

                                        text(name: 'customResourceFileContent',
                                                value: ''),

                                        booleanParam(name: 'createTestWorkspace',
                                                value: false)
                                ]
                    }
                }
            }
        }
    }
}