pipeline {
    agent { label 'rhel7-8gb' }

    options {
        timestamps()
        timeout(time: 2, unit: 'HOURS')
        buildDiscarder(logRotator(artifactDaysToKeepStr: '',
                artifactNumToKeepStr: '', daysToKeepStr: '60', numToKeepStr: '30'))
    }

    triggers { cron("@midnight") }

    parameters {
        string(name: 'emails',
                defaultValue: 'dnochevn@redhat.com',
                description: 'Comma-separated list of emails to send results')
    }

    stages {
        stage("Run E2E tests") {
            parallel {
                stage('Run Happy path tests against nightly build') {
                    steps {
                        build job: 'basic-MultiUser-Che-check-e2e-tests-against-k8s',
                                parameters: [
                                        string(name: 'cheImageRepo',
                                                value: 'eclipse/che-server'),

                                        string(name: 'cheImageTag',
                                                value: 'nightly'),

                                        booleanParam(name: 'buildChe',
                                                value: false),

                                        string(name: 'ghprbSourceBranch',
                                                value: 'master'),

                                        string(name: 'ghprbPullId',
                                                value: ''),

                                        string(name: 'e2eTestToRun',
                                                value: 'test-happy-path'),

                                        string(name: 'testWorkspaceDevfileUrl',
                                                value: 'https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml'),

                                        text(name: 'customResourceFileContent',
                                                value: ''),

                                        booleanParam(name: 'createTestWorkspace',
                                                value: true)
                                ]
                    }
                }

                stage('Run devfile tests against nightly build') {
                    steps {
                        build job: 'basic-MultiUser-Che-check-e2e-tests-against-k8s',
                                parameters: [
                                        string(name: 'cheImageRepo',
                                                value: 'eclipse/che-server'),

                                        string(name: 'cheImageTag',
                                                value: 'nightly'),

                                        booleanParam(name: 'buildChe',
                                                value: false),

                                        string(name: 'ghprbSourceBranch',
                                                value: 'master'),

                                        string(name: 'ghprbPullId',
                                                value: ''),

                                        string(name: 'e2eTestToRun',
                                                value: 'test-all-devfiles'),

                                        string(name: 'testWorkspaceDevfileUrl',
                                                value: ''),

                                        text(name: 'customResourceFileContent',
                                                value: ''),

                                        booleanParam(name: 'createTestWorkspace',
                                                value: false)
                                ]
                    }
                }
            }
        }
    }

    post {
        failure {
            script {
                if (emails != "") {
                    mail to: emails,
                        subject: "Jenkins Job $currentBuild.fullDisplayName has failed.",
                        body: "Build $currentBuild.absoluteUrl has failed."
                }
            }
        }
    }
}