pipeline {
    agent { label 'rhel7-8gb' }

    options {
        timestamps()
        timeout(time: 3, unit: 'HOURS')
        buildDiscarder(logRotator(artifactDaysToKeepStr: '',
                artifactNumToKeepStr: '', daysToKeepStr: '60', numToKeepStr: '30'))
    }

//    triggers { cron("@midnight") }
//
//    parameters {
//        string(name: 'emails',
//                defaultValue: 'dnochevn@redhat.com,kfoniok@redhat.com',
//                description: 'Comma-separated list of emails to send results')
//    }

    stages {
        stage("Run E2E tests") {
            parallel {
                stage('Run Happy path tests') {
                    steps {
                        build job: 'che16904-basic-MultiUser-Che-check-e2e-tests-against-k8s',
                                parameters: [
                                        string(name: 'cheImageRepo',
                                                value: 'quay.io/eclipse/che-server'),

                                        string(name: 'cheImageTag',
                                                value: 'nightly'),

                                        booleanParam(name: 'buildChe',
                                                value: false),

                                        string(name: 'ghprbSourceBranch',
                                                value: 'che#16904'),

                                        string(name: 'ghprbPullId',
                                                value: ''),

                                        string(name: 'e2eTestToRun',
                                                value: 'test-happy-path'),

                                        string(name: 'testWorkspaceDevfileUrl',
                                                value: 'https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml'),

                                        booleanParam(name: 'createTestWorkspace',
                                                value: true),

                                        string(name: 'e2eTestParameters',
                                                value: ''),

                                        string(name: 'chectlPackageUrl',
                                                value: ''),

                                        string(name: 'cheE2eImageTag',
                                                value: 'nightly')
                                ]
                       }
                }

            }
        }
    }

 //   post {
 //       failure {
 //           script {
 //               if (emails != "") {
 //                   mail to: emails,
 //                       subject: "Jenkins Job $currentBuild.fullDisplayName has failed.",
 //                       body: "Build $currentBuild.absoluteUrl has failed."
 //               }
 //           }
 //       }
 //   }
}