[id="che_keycloak_username_replacement__patterns_{context}"]
= `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+`

User name adjustment configuration. Che needs to use the usernames as part of K8s object names and labels and therefore has stricter requirements on their format than the identity providers usually allow (it needs them to be DNS-compliant). The adjustment is represented by comma-separated key-value pairs. These are sequentially used as arguments to the String.replaceAll function on the original username. The keys are regular expressions, values are replacement strings that replace the characters in the username that match the regular expression. The modified username will only be stored in the Che database and will not be advertised back to the identity provider. It is recommended to use DNS-compliant characters as replacement strings (values in the key-value pairs). Example: `\=-,@=-at-` changes `\` to `-` and `@` to `-at-` so the username `org\user@com` becomes `org-user-at-com.`


.Default value for `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+`
====
----
NULL
----
====

