[id="che_infra_openshift_project_{context}"]
= `+CHE_INFRA_OPENSHIFT_PROJECT+`

DEPRECATED - Do not change the value of this property otherwise the existing workspaces will loose data. Do not set it on new installations. Defines OpenShift namespace in which all workspaces will be created. If not set, every workspace will be created in a new project, where project name = workspace id It's possible to use `<username>` and `<userid>` placeholders (for example: `che-workspace-<username>`). In that case, new project will be created for each user. OpenShift OAuth or service account with permission to create new projects must be used. If the project pointed to by this property exists, it will be used for all workspaces. If it does not exist, the namespace specified by the `che.infra.kubernetes.namespace.default` will be created and used. This parameter is subject to removal in future releases. Legacy workspaces located in this namespace may become unreachable in future releases. See the documentation for possible next steps.


.Default value for `+che_infra_openshift_project+`
====
----

----
====

