[id="che_workspace_storage_available__types_{context}"]
= `+CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES+`

The configuration property that defines available values for storage types that clients such as the Dashboard should propose to users during workspace creation and update. Available values:   - `persistent`: Persistent Storage slow I/O but persistent.   - `ephemeral`: Ephemeral Storage allows for faster I/O but may have limited storage       and is not persistent.   - `async`: Experimental feature: Asynchronous storage is combination of Ephemeral       and Persistent storage. Allows for faster I/O and keep your changes, will backup on stop       and restore on start workspace.       Will work only if:           - `che.infra.kubernetes.pvc.strategy='common'`           - `che.limits.user.workspaces.run.count=1`           - `che.infra.kubernetes.namespace.allow_user_defined=false`           - `che.infra.kubernetes.namespace.default` contains `<username>`      in other cases remove `async` from the list.


.Default value for `+CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES+`
====
----
persistent,ephemeral,async
----
====

